Allow bare effecter as effect
jorgebucaran/hyperapp pull request #1075
Opened 2021-10-25 09:31 UTC by zaceno

The idea behind this PR is to create some more symmetry in the API. 

An action can be dispatched on it's own (a bare function):

```js
onclick: SomeAction
```

or with a custom payload:

```js
onclick: [SomeAction, {foo: 'bar'}]
```

But when returning effects from actions, they need to be given as tuples (in square brackets), regardless if the effecter function needs a payload or not. I e:

```js
const doSomethingFx = () =>  {alert('I did something')}

const JustDoSomething = (state) => [state, [doSomethingFx]]
```

This PR would allow giving just the bare effecter when it does not require any parameters:

```js
const JustDoSomething = (state) => [state, doSomethingFx]
```

I admit this is not a common need and thus not a huge deal. But the change is small, and make the api more flexible and symmetrical (imo) without violating any principles or any breaking changes.

2022-02-10 07:40 UTC, icylace requested changes
Only a couple tweaks need to happen and then I think we would be good to go !

2022-02-10 07:40 UTC, icylace commented on index.d.ts
> +    payload?: P
`payload?: P` doesn't pass my type tests but changing it back to `payload: P` will.

2022-02-10 07:40 UTC, icylace commented on index.d.ts
> +    | readonly [effecter: Effecter<S, P>, payload?: P]
`payload?: P` doesn't pass my type tests but changing it back to `payload: P` will.

2022-02-10 07:40 UTC, icylace commented on index.d.ts
> +  // An Effecter is the function that runs an effect
Please change this line to: `// An effecter is the function that runs an effect.`

😅

2022-02-10 08:57 UTC, zaceno commented
Thanks for the feedback @icylace ! Should be good now

2022-02-11 07:52 UTC, icylace approved these changes
I tested the corrections that were made and things look good !

2022-03-02 12:07 UTC, jorgebucaran approved these changes

2022-03-02 12:08 UTC, jorgebucaran commented on index.js
> +                (fx) => fx && fx !== true && (fx[0] || fx)(dispatch, fx[1]),
👍 `fx` can't be `false` when we check `fx[0] || fx`.

2022-03-02 12:08 UTC, jorgebucaran commented on index.js
> +                (fx) => fx && fx !== true && (fx[0] || fx)(dispatch, fx[1]),
Once we're in `fx[0] || fx`, `fx` can't be `false`, yeah?

2022-03-02 12:25 UTC, merged

2022-03-02 12:27 UTC, jorgebucaran commented
Thanks, @zaceno! Sorry for the long delay here, `2.0.21` is out with this change. 💯